import { C } from "../utils/theme.js";
import { RelPar, countHIO, isRoundSealed } from "../utils/helpers.jsx";

export default function LeaderboardTab({ me, playerStats, rounds, deleteRoundFromDB, leagueMatches }) {
  return (
    <div style={{display:"flex",flexDirection:"column",gap:14}}>
      <h2 style={{margin:0,fontSize:18}}>📊 Leaderboard</h2>
      <div style={{background:C.card,borderRadius:12,border:`1px solid ${C.border}`,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11,minWidth:400}}><thead><tr style={{background:C.accent}}><th style={{padding:"8px 6px",textAlign:"left"}}>#</th><th style={{padding:"8px 4px",textAlign:"left"}}>Player</th><th style={{padding:"8px 4px",textAlign:"center"}}>HDCP</th><th style={{padding:"8px 4px",textAlign:"center"}}>Rnds</th><th style={{padding:"8px 4px",textAlign:"center"}}>Best</th><th style={{padding:"8px 4px",textAlign:"center"}}>Avg</th><th style={{padding:"8px 4px",textAlign:"center"}}>🎯</th></tr></thead><tbody>{playerStats.map((p,i)=>(<tr key={p.name} style={{borderTop:`1px solid ${C.border}`,background:p.name===me?"rgba(74,170,74,0.06)":"transparent"}}><td style={{padding:"8px 6px",fontWeight:700,color:i===0?C.gold:i<3?C.greenLt:C.muted}}>{i+1}</td><td style={{padding:"8px 4px",fontWeight:600}}>{p.name}</td><td style={{padding:"8px 4px",textAlign:"center",fontWeight:700,color:p.handicap!=null&&p.handicap<0?C.greenLt:p.handicap!=null&&p.handicap>0?C.red:C.text}}>{p.handicap!=null?p.handicap:"-"}</td><td style={{padding:"8px 4px",textAlign:"center",color:C.muted}}>{p.rounds}</td><td style={{padding:"8px 4px",textAlign:"center"}}>{p.best??"-"}</td><td style={{padding:"8px 4px",textAlign:"center"}}>{p.avg??"-"}</td><td style={{padding:"8px 4px",textAlign:"center",color:"#ff6b00"}}>{p.holeInOnes||0}</td></tr>))}</tbody></table></div></div>
      <div style={{background:C.card,borderRadius:12,padding:14,border:`1px solid ${C.border}`}}><div style={{fontWeight:600,marginBottom:8}}>All Rounds</div>{rounds.map(r=>{const hio=r.holeInOnes||countHIO(r.scores)||0;const sealed=isRoundSealed(r,leagueMatches,me);return<div key={r.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"6px 0",borderBottom:`1px solid ${C.border}`,fontSize:12}}><div><span style={{fontWeight:600}}>{r.player}</span><span style={{color:C.muted,fontSize:10,marginLeft:6}}>{r.course}</span><span style={{color:C.muted,fontSize:10,marginLeft:6}}>{r.date}</span></div><div style={{display:"flex",gap:6,alignItems:"center"}}>{sealed?<span style={{color:C.muted,fontSize:11}}>🔒 Sealed</span>:r.hidden?<span style={{color:C.muted,fontSize:11}}>🙈</span>:<><span style={{fontWeight:700}}>{r.total}</span><RelPar s={r.total} p={r.par}/></>}{!sealed&&hio>0&&<span style={{fontSize:10,color:"#ff6b00"}}>🎯{hio}</span>}<button onClick={()=>{if(confirm(`Delete ${r.player}'s round?`))deleteRoundFromDB(r.id);}} style={{background:"transparent",border:"none",color:C.muted,cursor:"pointer",fontSize:10,opacity:0.5}}>🗑</button></div></div>;})}</div>
    </div>
  );
}
