import { S1_STANDINGS, S1_RESULTS, S1_PLAYOFFS } from "../data/league.js";
import { C, btnS } from "../utils/theme.js";

export default function LeagueTab({ leagueView, setLeagueView, leagueRdFilter, setLeagueRdFilter }) {
  const filteredResults = leagueRdFilter === "all" ? S1_RESULTS : S1_RESULTS.filter(r => r[2] === parseInt(leagueRdFilter));

  return (
    <div style={{display:"flex",flexDirection:"column",gap:14}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{margin:0,fontSize:18}}>🏆 Season 1</h2><span style={{background:"rgba(212,184,74,0.2)",color:C.gold,padding:"3px 10px",borderRadius:12,fontSize:11,fontWeight:600}}>Semifinals</span></div>
      <div style={{display:"flex",gap:4}}>{[["standings","Standings"],["results","Results"],["bracket","Bracket"]].map(([k,l])=>(<button key={k} onClick={()=>setLeagueView(k)} style={{flex:1,padding:"8px 4px",borderRadius:8,border:leagueView===k?`2px solid ${C.greenLt}`:`1px solid ${C.border}`,background:leagueView===k?C.accent:C.card,color:leagueView===k?C.white:C.muted,cursor:"pointer",fontSize:12,fontWeight:600}}>{l}</button>))}</div>
      {leagueView==="standings"&&<div style={{background:C.card,borderRadius:12,border:`1px solid ${C.border}`,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11,minWidth:520}}><thead><tr style={{background:C.accent}}><th style={{padding:"8px 6px",textAlign:"left"}}>#</th><th style={{padding:"8px 4px",textAlign:"left"}}>Player</th><th style={{padding:"8px 4px",textAlign:"center"}}>Pts</th><th style={{padding:"8px 4px",textAlign:"center"}}>W</th><th style={{padding:"8px 4px",textAlign:"center"}}>L</th><th style={{padding:"8px 4px",textAlign:"center"}}>T</th><th style={{padding:"8px 4px",textAlign:"center"}}>Adj+/-</th><th style={{padding:"8px 4px",textAlign:"center"}}>Avg</th><th style={{padding:"8px 4px",textAlign:"center"}}>Tot</th></tr></thead><tbody>{S1_STANDINGS.map((s,i)=>(<tr key={s.p} style={{borderTop:`1px solid ${C.border}`,background:i<7?"rgba(74,170,74,0.04)":"transparent"}}><td style={{padding:"8px 6px",fontWeight:700,color:i===0?C.gold:i<7?C.greenLt:C.muted}}>{i+1}</td><td style={{padding:"8px 4px",fontWeight:600,fontSize:11}}>{s.p}{s.seed>0&&<span style={{fontSize:9,color:C.gold,marginLeft:4}}>#{s.seed}</span>}</td><td style={{padding:"8px 4px",textAlign:"center",fontWeight:700,color:C.gold}}>{s.pts}</td><td style={{padding:"8px 4px",textAlign:"center",color:C.greenLt}}>{s.w}</td><td style={{padding:"8px 4px",textAlign:"center",color:C.red}}>{s.l}</td><td style={{padding:"8px 4px",textAlign:"center",color:C.muted}}>{s.t}</td><td style={{padding:"8px 4px",textAlign:"center",fontWeight:700,color:s.tAdj<0?C.greenLt:s.tAdj>0?C.red:C.muted}}>{s.tAdj>0?`+${s.tAdj}`:s.tAdj}</td><td style={{padding:"8px 4px",textAlign:"center"}}>{s.aScr}</td><td style={{padding:"8px 4px",textAlign:"center",color:C.muted}}>{s.tScr}</td></tr>))}</tbody></table></div><div style={{padding:"8px 12px",background:C.card2,fontSize:10,color:C.muted,borderTop:`1px solid ${C.border}`}}>Top 7 qualify for playoffs · Win=2pts, Tie=1pt</div></div>}
      {leagueView==="results"&&<><div style={{display:"flex",gap:4,flexWrap:"wrap"}}><button onClick={()=>setLeagueRdFilter("all")} style={{padding:"5px 10px",borderRadius:6,border:leagueRdFilter==="all"?`2px solid ${C.greenLt}`:`1px solid ${C.border}`,background:leagueRdFilter==="all"?C.accent:C.card2,color:C.text,cursor:"pointer",fontSize:10,fontWeight:600}}>All</button>{[1,2,3,4,5,6].map(rd=>(<button key={rd} onClick={()=>setLeagueRdFilter(String(rd))} style={{padding:"5px 10px",borderRadius:6,border:leagueRdFilter===String(rd)?`2px solid ${C.greenLt}`:`1px solid ${C.border}`,background:leagueRdFilter===String(rd)?C.accent:C.card2,color:C.text,cursor:"pointer",fontSize:10,fontWeight:600}}>R{rd}</button>))}</div>{filteredResults.map(r=>{const[gm,wk,rd,course,p1,s1,p2,s2,winner,diff]=r;return<div key={gm} style={{background:C.card,borderRadius:8,padding:"10px 12px",border:`1px solid ${C.border}`,display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:12}}><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontWeight:winner===p1?700:400,color:winner===p1?C.greenLt:C.text}}>{p1}</span><span style={{fontWeight:700,fontSize:14}}>{s1}</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:2}}><span style={{fontWeight:winner===p2?700:400,color:winner===p2?C.greenLt:C.text}}>{p2}</span><span style={{fontWeight:700,fontSize:14}}>{s2}</span></div></div><div style={{textAlign:"right",marginLeft:12,minWidth:80}}><div style={{fontSize:10,color:C.muted}}>{course}</div><div style={{fontSize:10,color:C.muted}}>Wk{wk} R{rd} Gm{gm}</div><div style={{fontWeight:700,fontSize:11,color:winner==="Tie"?C.muted:C.gold,marginTop:2}}>{winner==="Tie"?"Tie":diff}</div></div></div>;})}</>}
      {leagueView==="bracket"&&<div style={{display:"flex",flexDirection:"column",gap:10}}>
        <div style={{fontSize:13,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:2}}>Quarterfinals</div>
        {S1_PLAYOFFS.filter(g=>g[4]==="QF").map(g=>{const[gm,,,course,,p1,s1,p2,s2,winner,diff]=g;return<div key={gm} style={{background:C.card,borderRadius:8,padding:10,border:`1px solid ${C.border}`}}><div style={{fontSize:10,color:C.muted,marginBottom:4}}>{course} · Game {gm}</div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:winner===p1?700:400,color:winner===p1?C.greenLt:C.text}}>{p1}</span><span style={{fontWeight:700}}>{s1}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:winner===p2?700:400,color:winner===p2?C.greenLt:C.text}}>{p2}</span><span style={{fontWeight:700}}>{s2}</span></div>{winner&&<div style={{textAlign:"right",fontSize:10,color:C.gold,marginTop:4}}>Winner: {winner} ({diff})</div>}</div>;})}
        <div style={{fontSize:13,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:2,marginTop:8}}>Semifinals</div>
        <div style={{background:C.card,borderRadius:8,padding:10,border:`1px solid ${C.border}`}}><div style={{fontSize:10,color:C.muted,marginBottom:4}}>Maitland Palms · Game 34</div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:600}}>#1 Ryan Hangartner</span><span style={{color:C.muted}}>vs</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:600}}>Jeff Gurrister</span><span style={{color:C.gold,fontSize:10}}>In Progress</span></div></div>
        <div style={{background:C.card,borderRadius:8,padding:10,border:`1px solid ${C.border}`}}><div style={{fontSize:10,color:C.muted,marginBottom:4}}>Maitland Palms · Game 35</div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:600}}>#2 Jimmie Perkins</span><span style={{color:C.muted}}>vs</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:600}}>Jon Basorka</span><span style={{color:C.gold,fontSize:10}}>In Progress</span></div></div>
        <div style={{fontSize:13,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:2,marginTop:8}}>Finals</div>
        <div style={{background:C.card,borderRadius:8,padding:10,border:`1px solid ${C.gold}`,textAlign:"center"}}><div style={{fontSize:10,color:C.muted,marginBottom:4}}>Nebraska · Game 36</div><div style={{color:C.gold,fontWeight:700}}>🏆 TBD vs TBD</div><div style={{fontSize:10,color:C.muted,marginTop:4}}>Awaiting Semifinal Results</div></div>
      </div>}
    </div>
  );
}
