// ─── COURSE GENERATION (with dedup) ─────────────────────
export const RAND_NAMES=["Whistling Pines","Shadow Ridge","Eagle Bluff","Iron Horse","Cedar Valley","Falcon Crest","Timber Ridge","Stone Creek","Hawk's Landing","Silver Lakes","Canyon Ridge","Elk Run","Fox Hollow","Bear Creek","Wolf Run","Deer Path","Osprey Point","Heron Bay","Pelican Hill","Cypress Point","Magnolia Springs","Willow Bend","Oak Hollow","Maple Ridge","Pine Valley","Birch Creek","Aspen Hills","Cherry Blossom","Dogwood Trails","Juniper Hills","Sawgrass Bluffs","Dunes West","Seaside Links","Ocean Breeze","Windswept Dunes","Links at Stonebridge","Royal Palms","Grand Oaks","Heritage Pines","Plantation Bay","Marsh Harbor","Tidal Creek","Sunset Cove","Moonlight Bay","Starlight Ranch","Thunder Canyon","Lightning Ridge","Storm Peak","Whispering Oaks","Hidden Falls","Crystal Springs","Emerald Hills","Diamond Creek","Ruby Falls","Sapphire Bay","Golden Eagle","Bronze Bell","Copper Ridge","Ironwood","Steelhead Run","Summit Ridge","Vista Grande","Panorama Hills","Horizon Links","Skyline Bluffs","Prairie Wind","Tallgrass","Buffalo Run","Bison Ridge","Mustang Creek","Stallion Springs","Colt Meadow","Bronco Hills","Pinto Valley","Maverick Ridge","Lakeside Links","River Bend","Mill Creek","Bridge Valley","Covered Bridge","Old Mill Run","Waterford Glen","Canterbury Downs","Wellington Park","Sherwood Forest","Nottingham Links","Windsor Greens","Kingston Heath","Stratford Hills","Oxford Run","Cambridge Links","Princeton Oaks","Yale Ridge","Stanford Hills","Dartmouth Green","Ridgewood CC","Lakeview National","Mountain Shadows","Desert Springs","Coral Ridge","Palm Desert Dunes","Cactus Canyon","Mesa Verde","Red Rock Canyon","Sandstone Ridge","Limestone Creek","Granite Falls","Marble Ridge","Obsidian Links","Flint Hills","Cobblestone Creek","Fieldstone Manor"];

export function generateCourse(difficulty,existingNames=[]){
  const avail=RAND_NAMES.filter(n=>!existingNames.includes(n));
  const name=avail.length?avail[Math.floor(Math.random()*avail.length)]:`Course ${Math.floor(Math.random()*1000)}`;
  const templates=[[4,5,4,4,3,4,4,3,4,4,4,3,5,4,4,3,4,5],[4,4,4,4,3,5,4,3,5,4,4,3,4,5,4,3,4,5],[4,5,3,4,4,4,4,3,4,4,4,3,5,4,4,3,4,4],[4,4,4,3,5,4,3,4,5,4,4,3,4,5,4,4,3,4],[5,4,4,3,4,4,3,4,5,4,3,4,5,4,4,3,4,4]];
  const tmpl=templates[Math.floor(Math.random()*templates.length)];
  const dm={Easy:{bM:0.6,tight:0.1,mx:16},Medium:{bM:0.8,tight:0.25,mx:19},Hard:{bM:1.0,tight:0.45,mx:21},Expert:{bM:1.2,tight:0.65,mx:23}}[difficulty]||{bM:1,tight:0.3,mx:21};
  const hO=Array.from({length:18},(_,i)=>i);for(let i=17;i>0;i--){const j=Math.floor(Math.random()*(i+1));[hO[i],hO[j]]=[hO[j],hO[i]];}
  const holes=tmpl.map((par,i)=>{const hcp=hO.indexOf(i)+1;let base=par===3?Math.round((3+Math.random()*5)*dm.bM):par===4?Math.round((10+Math.random()*5)*dm.bM):Math.round((15+Math.random()*4)*dm.bM);base=Math.max(2,Math.min(dm.mx,base));const isTight=hcp<=6?Math.random()<dm.tight+0.4:hcp<=12?Math.random()<dm.tight:Math.random()<dm.tight*0.3;const spread=isTight?0:hcp<=6?Math.floor(Math.random()*2):hcp<=12?Math.floor(Math.random()*3):1+Math.floor(Math.random()*3);return{num:i+1,par,range:[Math.max(2,base),Math.min(dm.mx,Math.max(base,base+spread))]};});
  const seen=new Set();
  holes.forEach(h=>{const key=`${h.range[0]}-${h.range[1]}`;if(seen.has(key)){if(h.range[1]<dm.mx)h.range[1]+=1;else if(h.range[0]>2)h.range[0]-=1;else h.range[1]+=1;}seen.add(`${h.range[0]}-${h.range[1]}`);});
  return{name,level:difficulty,holes,generated:true};
}
